### ISSUE TITLE
Coco V3.0.0 crashes on opening non-cs-files

### ISSUE THREAD

**Issue by dreammaster38** [GeorgeAlexandria/CoCo#56]
I encounter regular crashes of Coco in Visual Studio 2017.
The error mainly occurs if i open files other then Cs-files (i.e. rdlc files, xml-files,....)

So here are the key data:
CoCo-Version 3.0.0
Visual Studio Version: Visual Studio 2017 Enterprise, V15.9.11

Error (logged in ActivityLog.xml):

`System.AggregateException: One or more errors occurred.
System.NullReferenceException: Object reference not set to an instance of an object.
at CoCo.Analyser.VisualStudioExtensions.GetLanguage(ITextBuffer buffer)
at CoCo.QuickInfo.QuickInfoSource..ctor(ITextBuffer textBuffer, IReadOnlyDictionary`2 quickInfoOptions, ITextDocumentFactoryService documentFactoryService)
at CoCo.Providers.QuickInfoProvider.<>;c__DisplayClass4_0.<TryCreateQuickInfoSource>b__0()
at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
at CoCo.Providers.QuickInfoProvider.TryCreateQuickInfoSource(ITextBuffer textBuffer)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.CreateSources(JoinableTaskContext joinableTaskContext, IEnumerable`1 orderedSourceProviders, ITextBuffer textBuffer, IList`1 failures)
--- End of inner exception stack trace ---
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.<UpdateAsync>d__32.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoPresentationSession.<UpdateAsync>d__5.MoveNext()&#x000D;&#x000A;---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
at CoCo.Analyser.VisualStudioExtensions.GetLanguage(ITextBuffer buffer)
at CoCo.QuickInfo.QuickInfoSource..ctor(ITextBuffer textBuffer, IReadOnlyDictionary`2 quickInfoOptions, ITextDocumentFactoryService documentFactoryService)
at CoCo.Providers.QuickInfoProvider.<>c__DisplayClass4_0.<TryCreateQuickInfoSource>b__0()
at Microsoft.VisualStudio.Utilities.PropertyCollection.GetOrCreateSingletonProperty[T](Object key, Func`1 creator)
at CoCo.Providers.QuickInfoProvider.TryCreateQuickInfoSource(ITextBuffer textBuffer)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.AsyncQuickInfoSession.CreateSources(JoinableTaskContext joinableTaskContext, IEnumerable`1 orderedSourceProviders, ITextBuffer textBuffer, IList`1 failures)`

**Comment by GeorgeAlexandria** [comment]
@dreammaster38, Thanks for you feedback!
Fix of this issue would be included to the next 3.1.0 version of CoCo. Currently I close this issue, but you can reopen it if you will have some exceptions on the new version.

**Comment by GeorgeAlexandria** [comment]
@dreammaster38, you can check a new version of extension. So let me know if you have still exceptions.
